import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FlightBookingService {
  flights = [{
    'id': 1,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1593140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543188800,
      'leavesVia': 1543189800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 600,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'arrivalAirport': 'Indira Gandhi',
    'arrivalTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 2,
    'from': 'Seattle',
    'fromCode': 'SEA',
    'to': 'Mumbai',
    'toCode': 'BOM',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 510,
    'carrier': 'Air China',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 3,
    'from': 'New York',
    'fromCode': 'JFK',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 520,
    'carrier': 'Air Canada',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 4,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 531,
    'carrier': 'Air France',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'star',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 5,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 570,
    'carrier': 'Swiss',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 6,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 539,
    'carrier': 'Turkish Airlines',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 7,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 563,
    'carrier': 'British Airways',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 8,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 579,
    'carrier': 'Emirates',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 9,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 621,
    'carrier': 'American',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'star',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 10,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325'
      },
    }],
    'price': 439,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 11,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 583,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'Non-refundable',
    'departAirport': 'Indira Gandhi',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 12,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1540461600,
    'arriveAt': 1543140000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }, {
      'via': 'london',
      'viaCode': 'LHR',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 576,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'star',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }];
  constructor() { }
  getFlights() {
    return this.flights;
  }

  getFlightById(id) {
    console.log(this.flights.find(flight => flight.id == id));
    return this.flights.find(flight => flight.id == id);
  }
}
