import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FlightBookingService {
  flights = [{
    'id': 1,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535155800000,
    'arriveAt': 1535278200000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535181000000,
      'leavesVia': 1535184600000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 600,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'arrivalAirport': 'Indira Gandhi',
    'arrivalTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 2,
    'from': 'Seattle',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SEA',
    'to': 'Mumbai',
    'toCode': 'BOM',
    'departureTime': 1535159400000,
    'arriveAt': 1535253000000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535188200000,
      'leavesVia': 1535190000000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 510,
    'carrier': 'Air China',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 3,
    'from': 'New York',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'JFK',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535163000000,
    'arriveAt': 1535249400000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535208000000,
      'leavesVia': 1535211600000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 520,
    'carrier': 'Air Canada',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Business',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 4,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535166600000,
    'arriveAt': 1535271000000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535193600000,
      'leavesVia': 1535197200000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 531,
    'carrier': 'Air France',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'star',
    'class': 'Business',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 5,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535170200000,
    'arriveAt': 1535285400000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535204400000,
      'leavesVia': 1535218800000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 570,
    'carrier': 'Swiss',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Business',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 6,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535173800000,
    'arriveAt': 1535281800000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535218800000,
      'leavesVia': 1535233200000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 539,
    'carrier': 'Turkish Airlines',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 7,
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535177400000,
    'arriveAt': 1535263800000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535226000000,
      'leavesVia': 1535230500000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 563,
    'carrier': 'British Airways',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 8,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535181000000,
    'arriveAt': 1535271000000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535219700000,
      'leavesVia': 1535223300000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 579,
    'carrier': 'Emirates',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 9,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535184600000,
    'arriveAt': 1535281800000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535223300000,
      'leavesVia': 1535226900000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 205,
    'carrier': 'American',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'star',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 10,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535188200000,
    'arriveAt': 1535274600000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535237700000,
      'leavesVia': 1535239200000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 439,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 11,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535191800000,
    'arriveAt': 1535289000000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535232000000,
      'leavesVia': 1535235600000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 583,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'Non-refundable',
    'departAirport': 'Indira Gandhi',
    'alliance': 'one world',
    'class': 'Business',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 12,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535195400000,
    'arriveAt': 1535290200000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1543147200,
      'leavesVia': 1543148800,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 576,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'star',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 13,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535199000000,
    'arriveAt': 1535293800000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535242800000,
      'leavesVia': 1535245400000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 600,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'arrivalAirport': 'Indira Gandhi',
    'arrivalTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 14,
    'from': 'Seattle',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SEA',
    'to': 'Mumbai',
    'toCode': 'BOM',
    'departureTime': 1535202600000,
    'arriveAt': 1535283000000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535239200000,
      'leavesVia': 1535244600000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 510,
    'carrier': 'Air China',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 15,
    'fromZone': '-0700',
    'toZone': '+0530',
    'from': 'New York',
    'fromCode': 'JFK',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535206200000,
    'arriveAt': 1535293800000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535255400000,
      'leavesVia': 1535259000000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 520,
    'carrier': 'Air Canada',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Business',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 16,
    'fromZone': '-0700',
    'toZone': '+0530',
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535209800000,
    'arriveAt': 1535304600000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535255400000,
      'leavesVia': 1535262600000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 531,
    'carrier': 'Air France',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'star',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 17,
    'fromZone': '-0700',
    'toZone': '+0530',
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535213400000,
    'arriveAt': 1535304600000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535265300000,
      'leavesVia': 1535276100000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 570,
    'carrier': 'Swiss',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 18,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535217000000,
    'arriveAt': 1535312100000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535276100000,
      'leavesVia': 1535279700000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 539,
    'carrier': 'Turkish Airlines',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Business',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 19,
    'from': 'San Francisco',
    'fromZone': '-0700',
    'toZone': '+0530',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535220600000,
    'arriveAt': 1535315700000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535279700000,
      'leavesVia': 1535286900000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 563,
    'carrier': 'British Airways',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 20,
    'fromZone': '-0700',
    'toZone': '+0530',
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535224200000,
    'arriveAt': 1535319300000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535286900000,
      'leavesVia': 1535290500000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 579,
    'carrier': 'Emirates',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'sky',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 21,
    'fromZone': '-0700',
    'toZone': '+0530',
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535227800000,
    'arriveAt': 1535326500000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535304900000,
      'leavesVia': 1535312100000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 621,
    'carrier': 'American',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'star',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 22,
    'fromZone': '-0700',
    'toZone': '+0530',
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535231400000,
    'arriveAt': 1535326500000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535312100000,
      'leavesVia': 1535317500000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 439,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 23,
    'fromZone': '-0700',
    'toZone': '+0530',
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535235000000,
    'arriveAt': 1535327400000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535306700000,
      'leavesVia': 1535309400000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 583,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'Non-refundable',
    'departAirport': 'Indira Gandhi',
    'alliance': 'one world',
    'class': 'Economy',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }, {
    'id': 24,
    'fromZone': '-0700',
    'toZone': '+0530',
    'from': 'San Francisco',
    'fromCode': 'SFO',
    'to': 'New Delhi',
    'toCode': 'DEL',
    'departureTime': 1535238600000,
    'arriveAt': 1535323800000,
    'layOverDetails': [{
      'via': 'london',
      'viaCode': 'LHR',
      'viaTimeZone': '+0100',
      'arrivesAtVia': 1535284200000,
      'leavesVia': 1535287800000,
      'viaAirport': 'heathrow',
      'arriveAtTerminal': 'T-1',
      'leavesAtTerminal': 'T-3',
      'layOverCarrier': 'British Airways',
      'layOverAircraft': 'A325',
      'layOverFareType': 'partially-refundable',
      'layOverAlliance': 'sky',
      'layOverConvenienceAvailable': {
        'internet': '25Mbps',
        'aircraft': 'Airbus A325',
        'meal': 'free',
        'entertainment': 'english, hindi, italian'
      },
    }],
    'price': 576,
    'carrier': 'Air India',
    'name': 'AI173',
    'convenienceAvailable': {
      'internet': '25Mbps',
      'aircraft': 'Airbus A325',
      'meal': 'free',
      'entertainment': 'english, hindi, italian'
    },
    'aircraft': 'A325',
    'departAirport': 'Indira Gandhi',
    'fromTerminal': 'Indira Gandhi - T-3',
    'fareType': 'partially-refundable',
    'alliance': 'star',
    'class': 'Business',
    'arriveAirport': 'SFO international',
    'toTerminal': 'T-1',
    'baggage': '5-7 kgs',
    'noOfBaggages': 2
  }];
  constructor() { }
  getFlights() {
    return this.flights;
  }

  getFlightById(id) {
    console.log(this.flights.find(flight => flight.id == id));
    return this.flights.find(flight => flight.id == id);
  }
}
